on:
  push:
    branches: [main]
  repository_dispatch:
    type: [repo-dispatch]
  
  name: Build and deploy notes saver app
  
  jobs:
    build_and_deploy:
      name: Build & Deploy
      runs-on: ubuntu-latest
      
